### PR TITLE
Force C++ only build

### PR DESCRIPTION
**Pull request by Jazzinghen**
Remove C checks in Cmake Lists to make our Unreal Engine 4 life easier.

### CODE REVIEW

**Comment by jeffreykxiao** [comment]
its_me_dong

**Review by jeffreykxiao — APPROVED** [review]
I guess it really do be like that.

**Comment by haisongdong-harrison** [comment]
who summoned the almighty one

**Review by haisongdong-harrison — APPROVED** [review]
we do this too for C++ and CUDA
I just didn't know this can make it faster

**Comment by haudren** [comment]
Probably not faster, but you don't need the C toolchain to be working :D

**Review by haudren — APPROVED** [review]

**Comment by Jazzinghen** [comment]
> we do this too for C++ and CUDA
> I just didn't know this can make it faster

It isn't for speed. It's for sanity.

**Comment by haisongdong-harrison** [comment]
Oh I read the description wrong
I thought you said to make UE4 life faster

**Pull request merged**
